name: Docker CI Action
on:
  push:
    branches: main
    paths: hello-world-docker-action/**
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run my own container
        uses: ./hello-world-docker-action
        id: docker-action
        with: 
          who-to-greet: 'seretana'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
    
